### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by CaryWRCampbell** [MrPowers/frontend-generators#16]
The command "bundle exec rake add_assets:bootstrap" fails with Rails 5.0.1:

```
Corea:grayscale_codecraft carycampbell$ bundle exec rake add_assets:bootstrap
rake aborted!
Don't know how to build task 'add_assets:bootstrap' (see --tasks)
/Users/carycampbell/.gem/ruby/2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/carycampbell/.gem/ruby/2.3.1/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
/Users/carycampbell/.gem/ruby/2.3.1/bin/bundle:23:in `load'
/Users/carycampbell/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

Is your gem supposed to support the Rails 5.0.1 version?

Thanks in advance for your help!

**Comment by MrPowers** [comment]
Thanks for opening the issue.  I'm not working with Rails anymore, so I won't be adding this feature, but I definitely would love to transition this project to someone that would like to keep it updated. Feel free to send a pull request if you'd like to get involved with the project!  Thanks for opening the issue!

**Comment by rhuberdeau** [comment]
This is working for me on 5.0.2. 

@CaryWRCampbell  Are you sure you added `require "frontend_generators"` and `load 'tasks/add_assets.rake'` to your rake file?

**Comment by MrPowers** [comment]
@rhuberdeau - Can you please email me?  I'd like to chat with you about this project and see if you're interested in contributing 😄

**Comment by bermannoah** [comment]
@MrPowers: Hey -- I can confirm that this is working for me on 5.0.2 as well. I was unable to duplicate the error above, though if I didn't add (or misplaced) the Rakefile additions I would get a similar (if shorter) error.

**Comment by rhuberdeau** [comment]
Seems like OP missed a step. Closing the ticket.

**Comment by MrPowers** [comment]
Thanks @rhuberdeau and @bermannoah 😄
